### ISSUE TITLE
test_upgrade.StorageCompatibilityTest is flaky

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate-qa#135]
```
======================================================================
ERROR: test_upgrade_paths (test_upgrade.StorageCompatibilityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/bwc/test_upgrade.py", line 160, in test_upgrade_paths
    self._test_upgrade_path(path, nodes=3)
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/bwc/test_upgrade.py", line 217, in _test_upgrade_path
    self.assert_data_persistence(version_def, nodes, digest)
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/bwc/test_upgrade.py", line 232, in assert_data_persistence
    cursor.execute('ALTER TABLE doc.t1 SET ("refresh_interval" = 4000)')
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/env/lib/python3.7/site-packages/crate/client/cursor.py", line 54, in execute
    bulk_parameters)
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/env/lib/python3.7/site-packages/crate/client/http.py", line 328, in sql
    content = self._json_request('POST', self.path, data=data)
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/env/lib/python3.7/site-packages/crate/client/http.py", line 448, in _json_request
    _raise_for_status(response)
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/env/lib/python3.7/site-packages/crate/client/http.py", line 187, in _raise_for_status
    error_trace=error_trace)
crate.client.exceptions.ProgrammingError: SQLActionException[RelationUnknown: Relation 'doc.t1' unknown]
```

**Comment by mfussenegger** [comment]
Hasn't failed in a while, so I'm closing this.
