### ISSUE TITLE
bwc.test_upgrade.StorageCompatibilityTest fails because of java home is not found in cr8's cache

### ISSUE THREAD

**Issue by marregui** [crate/crate-qa#156]
As I run:

```
python -m unittest -v test_upgrade.StorageCompatibilityTest
```
from within `crate-qa/tests/bwc`, I get:

```
130 actionable tasks: 97 executed, 33 up-to-date
Already on '4.2'
Your branch is up to date with 'origin/4.2'.
From https://github.com/crate/crate
 * branch                  4.2        -> FETCH_HEAD
Already up to date.
Already on '4.2'
Your branch is up to date with 'origin/4.2'.
From https://github.com/crate/crate
 * branch                  4.2        -> FETCH_HEAD
Already up to date.
/Users/marregui/.cache/cr8/crates/crate-4.3.0-202007270003-862b289/bin/crate: line 129: /Users/marregui/.cache/cr8/crates/crate-4.3.0-202007270003-862b289/jdk/Contents/Home/bin/java: No such file or directory
/Users/marregui/.cache/cr8/crates/crate-4.3.0-202007270003-862b289/bin/crate: line 129: exec: /Users/marregui/.cache/cr8/crates/crate-4.3.0-202007270003-862b289/jdk/Contents/Home/bin/java: cannot execute: No such file or directory
/Users/marregui/.cache/cr8/crates/crate-4.3.0-202007270003-862b289/bin/crate: line 129: /Users/marregui/.cache/cr8/crates/crate-4.3.0-202007270003-862b289/jdk/Contents/Home/bin/java: No such file or directory
/Users/marregui/.cache/cr8/crates/crate-4.3.0-202007270003-862b289/bin/crate: line 129: exec: /Users/marregui/.cache/cr8/crates/crate-4.3.0-202007270003-862b289/jdk/Contents/Home/bin/java: cannot execute: No such file or directory
/Users/marregui/.cache/cr8/crates/crate-4.3.0-202007270003-862b289/bin/crate: line 129: /Users/marregui/.cache/cr8/crates/crate-4.3.0-202007270003-862b289/jdk/Contents/Home/bin/java: No such file or directory
/Users/marregui/.cache/cr8/crates/crate-4.3.0-202007270003-862b289/bin/crate: line 129: exec: /Users/marregui/.cache/cr8/crates/crate-4.3.0-202007270003-862b289/jdk/Contents/Home/bin/java: cannot execute: No such file or directory
Removed server http://127.0.0.1:4200 from active pool
ERROR

======================================================================
ERROR: test_upgrade_paths (test_upgrade.StorageCompatibilityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
```

I fell into this whilst trying to reproduce [this](https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate-qa/detail/crate-qa/1158/pipeline/).

**Comment by marregui** [comment]
Reported in https://github.com/mfussenegger/cr8/issues/311 same issue.
