### ISSUE TITLE
SystemExit: CrateDB didn't start in time or couldn't form a cluster

### ISSUE THREAD

**Issue by amotl** [crate/crate-qa#186]
Hi there,

currently, the _Python bwc tests_ fail more often than not with the scenario that CrateDB isn't able to form a cluster. I wanted to collect some traces here in order to assist on investigating this.

With kind regards,
Andreas.

cc @mkleen

**Comment by amotl** [comment]
For example, at [1].

[1] https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa_on_pr/detail/crate_qa_on_pr/521/pipeline/21


<details>
<summary>Java traceback</summary>

```java
[2021-02-03T16:26:57,724][INFO ][o.e.c.c.JoinHelper       ] [ab6d7e1c1d8a-2] failed to join {ab6d7e1c1d8a-1}{TQxFvAyMQYmuukI8-EYohA}{6BM9An5mQoyebYNK84qx6Q}{127.0.0.1}{127.0.0.1:4302}{http_address=127.0.0.1:4202} with JoinRequest{sourceNode={ab6d7e1c1d8a-2}{XGSX5CMORkypIqMplkbhCg}{82NMWrUzSDO-ZbaLoXJOCQ}{127.0.0.1}{127.0.0.1:4300}{http_address=127.0.0.1:4200}, optionalJoin=Optional[Join{term=2, lastAcceptedTerm=1, lastAcceptedVersion=14, sourceNode={ab6d7e1c1d8a-2}{XGSX5CMORkypIqMplkbhCg}{82NMWrUzSDO-ZbaLoXJOCQ}{127.0.0.1}{127.0.0.1:4300}{http_address=127.0.0.1:4200}, targetNode={ab6d7e1c1d8a-1}{TQxFvAyMQYmuukI8-EYohA}{6BM9An5mQoyebYNK84qx6Q}{127.0.0.1}{127.0.0.1:4302}{http_address=127.0.0.1:4202}}]}
org.elasticsearch.transport.RemoteTransportException: [ab6d7e1c1d8a-1][127.0.0.1:4302][internal:cluster/coordination/join]
Caused by: java.lang.IllegalStateException: failure when sending a validation request to node
	at org.elasticsearch.cluster.coordination.Coordinator$3.onFailure(Coordinator.java:476) ~[crate-app.jar:4.5.0-202102030003-9d281f0]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:62) ~[crate-app.jar:4.5.0-202102030003-9d281f0]
	at org.elasticsearch.transport.TransportService$TimeoutResponseHandler.handleException(TransportService.java:1092) ~[crate-app.jar:4.5.0-202102030003-9d281f0]
	at org.elasticsearch.transport.InboundHandler.lambda$handleException$2(InboundHandler.java:246) ~[crate-app.jar:4.5.0-202102030003-9d281f0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.elasticsearch.transport.RemoteTransportException: [ab6d7e1c1d8a-2][127.0.0.1:4300][internal:cluster/coordination/join/validate]
Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.metadata.Metadata$Custom][license]
	at org.elasticsearch.common.io.stream.NamedWriteableRegistry.getReader(NamedWriteableRegistry.java:113) ~[crate-app.jar:4.5.0-202102030003-9d281f0]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:45) ~[crate-app.jar:4.5.0-202102030003-9d281f0]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:39) ~[crate-app.jar:4.5.0-202102030003-9d281f0]
	at org.elasticsearch.cluster.metadata.Metadata.readFrom(Metadata.java:779) ~[crate-app.jar:4.5.0-202102030003-9d281f0]
	at org.elasticsearch.cluster.ClusterState.readFrom(ClusterState.java:717) ~[crate-app.jar:4.5.0-202102030003-9d281f0]
	at org.elasticsearch.cluster.coordination.ValidateJoinRequest.<init>(ValidateJoinRequest.java:39) ~[crate-app.jar:4.5.0-202102030003-9d281f0]
	at org.elasticsearch.transport.RequestHandlerRegistry.newRequest(RequestHandlerRegistry.java:56) ~[crate-app.jar:4.5.0-202102030003-9d281f0]
	at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:180) [crate-app.jar:4.5.0-202102030003-9d281f0]
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:115) [crate-app.jar:4.5.0-202102030003-9d281f0]
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:104) [crate-app.jar:4.5.0-202102030003-9d281f0]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:701) [crate-app.jar:4.5.0-202102030003-9d281f0]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) [crate-app.jar:4.5.0-202102030003-9d281f0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) [netty-handler-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.58.Final.jar:4.1.58.Final]
	at java.lang.Thread.run(Thread.java:832) ~[?:?]
ERROR
```
</details>

```python
ERROR: test_auto_expand_indices_during_rolling_upgrade (test_recovery.RecoveryTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/bwc/test_recovery.py", line 527, in test_auto_expand_indices_during_rolling_upgrade
    self._run_upgrade_paths(self._test_auto_expand_indices_during_rolling_upgrade, UPGRADE_PATHS_FROM_43)
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/bwc/test_recovery.py", line 104, in _run_upgrade_paths
    test(p)
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/bwc/test_recovery.py", line 554, in _test_auto_expand_indices_during_rolling_upgrade
    self._upgrade_to_mixed_cluster(cluster, path.to_version)
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/bwc/test_recovery.py", line 98, in _upgrade_to_mixed_cluster
    self._upgrade_cluster(cluster, version, 1)
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/bwc/test_recovery.py", line 88, in _upgrade_cluster
    new_node = self.upgrade_node(node, version)
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/src/crate/qa/tests.py", line 225, in upgrade_node
    new_node.start()
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/env/lib/python3.7/site-packages/cr8/run_crate.py", line 365, in start
    raise SystemExit("CrateDB didn't start in time or couldn't form a cluster.") from None
SystemExit: CrateDB didn't start in time or couldn't form a cluster.
```

**Comment by mkleen** [comment]
Thanks, i will have a look!

**Comment by mkleen** [comment]
I think this might be related to the recent license change

```
Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.metadata.Metadata$Custom][license]
```

**Comment by amotl** [comment]
Hi @mkleen,

as discussed before, will you add another patch on top of https://github.com/crate/crate/pull/10992 before this will get stable again? I am just asking out of curiosity.

With kind regards,
Andreas.

**Comment by mkleen** [comment]
Yes sure!

**Comment by mkleen** [comment]
https://github.com/crate/crate/pull/11009
