### ISSUE TITLE
BWC tests are failing very regularly

### ISSUE THREAD

**Issue by amotl** [crate/crate-qa#244]
Hi there,

@matriv reported that the BWC tests are failing very regularly, sometimes with timeouts, sometimes with 500 server errors. An example is [^1].

With kind regards,
Andreas.

[^1]: https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa/detail/crate_qa/377/pipeline/30

**Comment by BaurzhanSakhariev** [comment]
Error message:

```
ERROR: test_upgrade_paths (test_upgrade.StorageCompatibilityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa/tests/bwc/test_upgrade.py", line 160, in test_upgrade_paths
    self._test_upgrade_path(path, nodes=3)
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa/tests/bwc/test_upgrade.py", line 190, in _test_upgrade_path
    digest = container.put(BytesIO(b'sample data'))
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa/env/lib/python3.8/site-packages/crate/client/blob.py", line 67, in put
    created = self.conn.client.blob_put(self.container_name,
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa/env/lib/python3.8/site-packages/crate/client/http.py", line 440, in blob_put
    _raise_for_status(response)
  File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa/env/lib/python3.8/site-packages/crate/client/http.py", line 209, in _raise_for_status
    raise ProgrammingError(message)
crate.client.exceptions.ProgrammingError: 500 Server Error: Internal Server Error

```

**Comment by matriv** [comment]
We'd probably need to expose the crate node logs to get some help.
I have played around a bit and never managed to make it fail locally so far.

**Comment by mfussenegger** [comment]
Could probably use a similar pattern to what we did in crate to dump the server logs on errors:

https://github.com/crate/crate/commit/2849a2cee64eed02d030cc55ea7357767119eff9

**Comment by matriv** [comment]
There is again failure regarding the blob test, reopening.

**Comment by mfussenegger** [comment]
Should be fixed with https://github.com/crate/crate-qa/pull/267

![image](https://user-images.githubusercontent.com/38700/232471028-4b8affce-415f-4ce4-addd-c9fccc8a42ab.png)
